annotations:
  - border_color: '#808080FF'
    border_radius: 0
    border_style: ''
    color: '#DEF5CE'
    rotation: 0
    thickness: 1
    type: rectangle
    x1: -320.0
    y1: -400.0
    x2: 400.0
    y2: 240.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      BGP ASN: 65000
      Lo0: 198.18.255.255
      Eth0/0: 192.168.12.1
      Eth0/1: 192.168.120.1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -280.0
    y1: -360.0
    z_index: 1
  - border_color: '#808080FF'
    border_radius: 0
    border_style: ''
    color: '#CEF5EB'
    rotation: 0
    thickness: 1
    type: rectangle
    x1: -320.0
    y1: -160.0
    x2: 400.0
    y2: 280.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      BGP ASN: 65100
      Lo0: 198.18.255.254
      GigabitEthernet1: 192.168.12.2
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -280.0
    y1: 40.0
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      Username: localadmin
      Password: C1sco12345
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -600.0
    y1: -200.0
    z_index: 1
  - border_color: '#000000'
    border_radius: 0
    border_style: ''
    color: '#B2DDFF'
    rotation: 0
    thickness: 1
    type: rectangle
    x1: -640.0
    y1: -280.0
    x2: 280.0
    y2: 240.0
    z_index: 0
smart_annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: iosxe_config.txt
        content: |-
          hostname Customer-Edge
          !
          no logging console
          aaa new-model
          !
          aaa authentication login default local
          aaa authentication enable default none
          aaa authorization exec default local if-authenticated
          !
          ip domain name dcloud.cisco.com
          !
          username localadmin privilege 15 secret 9 $9$3qxfLNd9ajoZXU$Z1rHALIl8roOVl/DSJYoLTRslhwOPsgCv.DmAYtDMNE
          !
          interface Loopback0
           ip address 198.18.255.254 255.255.255.255
          !
          interface GigabitEthernet1
           ip address 192.168.12.2 255.255.255.0
           no shutdown
          !
          router bgp 65100
           bgp router-id 198.18.255.254
           bgp log-neighbor-changes
           redistribute connected
           neighbor 192.168.12.1 remote-as 65000
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: c8000v-17-18-2
    label: Customer-Edge
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: -40
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        type: physical
        slot: 0
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        type: physical
        slot: 1
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        type: physical
        slot: 2
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        type: physical
        slot: 3
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname Provider-Edge
          !
          no logging console
          aaa new-model
          !
          aaa authentication login default local
          aaa authentication enable default none
          aaa authorization exec default local if-authenticated
          !
          ip dhcp pool JUMPBOX
           network 192.168.100.0 255.255.255.0
           default-router 192.168.100.1
          !
          username localadmin privilege 15 secret 9 $9$retcwQLXtJPTaU$nKz2T38AUUK9XnI7yHiWzg7WkyJ1NGkfzSHLmRflEZA
          !
          interface Loopback0
           ip address 198.18.255.255 255.255.255.255
          !
          interface Ethernet0/0
           ip address 192.168.12.1 255.255.255.0
          !
          interface Ethernet0/1
           ip address 192.168.120.1 255.255.255.0
          !
          interface Ethernet0/2
           no ip address
           shutdown
          !
          interface Ethernet0/3
           ip address 192.168.100.1 255.255.255.0
          !
          router bgp 65000
           bgp router-id 198.18.255.255
           bgp log-neighbor-changes
           redistribute connected
           neighbor 192.168.12.2 remote-as 65100
           neighbor 192.168.120.2 remote-as 65100
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: Provider-Edge
    node_definition: iol-xe
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: -240
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: Ethernet0/0
        mac_address: null
        type: physical
        slot: 0
      - id: i2
        label: Ethernet0/1
        mac_address: null
        type: physical
        slot: 1
      - id: i3
        label: Ethernet0/2
        mac_address: null
        type: physical
        slot: 2
      - id: i4
        label: Ethernet0/3
        mac_address: null
        type: physical
        slot: 3
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |
          # this is a shell script which will be sourced at boot
          hostname Jumpbox
          # configurable user account
          USERNAME=localadmin
          PASSWORD=C1sco12345
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: Jumpbox
    node_definition: desktop
    parameters: {}
    ram: null
    tags: []
    x: 40
    y: -280
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        type: physical
        slot: 0
links:
  - id: l0
    n1: n1
    n2: n2
    i1: i4
    i2: i0
    conditioning: {}
    label: Provider-Edge-Ethernet0/3<->Jumpbox-eth0
  - id: l1
    n1: n0
    n2: n1
    i1: i1
    i2: i1
    conditioning: {}
    label: Customer-Edge-GigabitEthernet1<->Provider-Edge-Ethernet0/0
lab:
  description: ''
  notes: |-
    # Verify Connectivity
    1. Connect to Jumpbox console
    2. ping Customer-Edge loopback: `ping 198.18.255.254`

    # Stage Your Change
    1. Create an ACM save point: `Customer-Edge# acm save flash:/before_big_change`
    2. Create an ACM configlet: `Customer-Edge# acm configlet create mybigchange`
    ```
    int gi1
     ip address 192.168.120.2 255.255.255.0
    !
    router bgp 65100
    no neighbor 192.168.12.1
    neighbor 192.168.120.1
    end
    ```

    # Validate, Implement, and Commit Your Change
    1. Verify your configlet: `Customer-Edge# acm configlet status`
    2. Validate your configlet: `Customer-Edge#acm merge mybigchange validate`
    3. Implement your change with automatic revert after 5 minutes: `Customer-Edge# acm merge mybigchange timeout 300`
    4. Simulate moving the Customer-Edge router to a new ISP:
        1. Delete the link between Provider-Edge and Customer-Edge
        2. Create a new link between Provider-Edge E0/1 and Customer-Edge Gi1
    5. Verify BGP neighborship is established: `Customer-Edge# show ip bgp summary`
    6. From Jumpbox: `ping 198.18.255.254`
    7. Commit the change `Customer-Edge# acm confirm-commit`

    # Rollback
    1. See what the rollback will do: `Customer-Edge# acm rollback 1 diff`
    2. Revert the cable change made earlier
        1. Delete the link between Provider-Edge and Customer-Edge
        2. Create a new link between Provider-Edge E0/0 and Customer-Edge Gi1
    3. Rollback `Customer-Edge# acm rollback 1`
    4. Verify BGP neighborship is established: `Customer-Edge# show ip bgp summary`
    5. From Jumpbox: `ping 198.18.255.254`
  title: Atomic Config Manager
  version: 0.3.0
